services:
  # Databases
  metricbox-postgresql:
    image: postgres:15
    container_name: metricbox-postgresql
    environment:
      POSTGRES_DB: metricbox
      POSTGRES_USER: metricbox
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./configs/database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metricbox"]
      interval: 5s
      timeout: 5s
      retries: 5

  metricbox-clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: metricbox-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse      
      - ./.build/custom-users.xml:/etc/clickhouse-server/users.d/custom-users.xml:ro
    environment:
      CLICKHOUSE_DB: metricbox      
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1

  metricbox-redis:
    image: redis:7-alpine
    container_name: metricbox-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes

  # MetricBox Core Services
  metricbox-event-ingestion:
    build: 
      context: ./services/event-ingestion
    container_name: metricbox-event-ingestion
    ports:
      - "8081:${CLICKHOUSE_PUB_PORT}"
      - "9090:9090"
    depends_on:
      metricbox-clickhouse:
        condition: service_started
      metricbox-redis:
        condition: service_started
    environment:
      SERVICE_NAME: metricbox-event-ingestion
      REDIS_URL: redis://metricbox-redis:6379
      CLICKHOUSE_URL: metricbox-clickhouse:8123
      CLICKHOUSE_DB: metricbox      
      CLICKHOUSE_PUB_USER_PWD: ${CLICKHOUSE_PUB_USER_PWD}
      CLICKHOUSE_PUB_PORT: ${CLICKHOUSE_PUB_PORT}
      CLICKHOUSE_ADMIN_USER_PWD: ${CLICKHOUSE_ADMIN_USER_PWD}
      CLICKHOUSE_ADMIN_PORT: ${CLICKHOUSE_ADMIN_PORT}
    volumes:
      - ./logs:/app/logs

  metricbox-query-service:
    build: 
      context: ./services/query-service
    container_name: metricbox-query-service
    ports:
      - "8082:8080"
    depends_on:
      metricbox-clickhouse:
        condition: service_started
      metricbox-redis:
        condition: service_started
    environment:
      - CLICKHOUSE_URL=http://metricbox-clickhouse:8123
      - REDIS_URL=redis://metricbox-redis:6379
      - SERVICE_NAME=metricbox-query-service

  metricbox-user-management:
    build: 
      context: ./services/user-management
    container_name: metricbox-user-management
    ports:
      - "8083:8080"
    depends_on:
      metricbox-postgresql:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://metricbox:password@metricbox-postgresql:5432/metricbox
      - SERVICE_NAME=metricbox-user-management

  metricbox-dashboard-service:
    build: 
      context: ./services/dashboard-service
    container_name: metricbox-dashboard-service
    ports:
      - "8084:8080"
    depends_on:
      metricbox-postgresql:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://metricbox:password@metricbox-postgresql:5432/metricbox
      - SERVICE_NAME=metricbox-dashboard-service

  metricbox-notification-service:
    build: 
      context: ./services/notification-service
    container_name: metricbox-notification-service
    ports:
      - "8085:8080"
    depends_on:
      metricbox-postgresql:
        condition: service_healthy
      metricbox-redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://metricbox:password@metricbox-postgresql:5432/metricbox
      - REDIS_URL=redis://metricbox-redis:6379
      - SERVICE_NAME=metricbox-notification-service

  metricbox-api-gateway:
    build: 
      context: ./services/api-gateway
    container_name: metricbox-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - metricbox-user-management
      - metricbox-event-ingestion
      - metricbox-query-service
      - metricbox-dashboard-service
    environment:
      - USER_SERVICE_URL=http://metricbox-user-management:8080
      - INGESTION_SERVICE_URL=http://metricbox-event-ingestion:8080
      - QUERY_SERVICE_URL=http://metricbox-query-service:8080
      - DASHBOARD_SERVICE_URL=http://metricbox-dashboard-service:8080
      - SERVICE_NAME=metricbox-api-gateway

  metricbox-data-generator:
    build: 
      context: ./services/data-generator
    container_name: metricbox-data-generator
    depends_on:
      - metricbox-event-ingestion
    environment:
      - INGESTION_URL=http://metricbox-event-ingestion:8080
      - EVENTS_PER_SECOND=100
      - SERVICE_NAME=metricbox-data-generator

  # Monitoring Stack
  metricbox-prometheus:
    image: prom/prometheus:latest
    container_name: metricbox-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

  metricbox-grafana:
    image: grafana/grafana:latest
    container_name: metricbox-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/etc/grafana/provisioning
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/metricbox-overview.json

  metricbox-jaeger:
    image: jaegertracing/jaeger:2.0.0
    container_name: metricbox-jaeger
    ports:
      - "16686:16686"    # UI
      - "4317:4317"      # OTLP gRPC
      - "4318:4318"      # OTLP HTTP
    environment:
      - SPAN_STORAGE_TYPE=memory

networks:
  default:
    name: metricbox-network

volumes:
  postgresql_data:
  clickhouse_data:
  redis_data:
  prometheus_data:
  grafana_data: