

GET http://localhost:8081/health

###
POST http://localhost:8081/api/events
Content-Type: application/json

{
  "msg": "hello"
}

###
POST http://localhost:9090/admin/tenant/1234

###
DELETE http://localhost:9090/admin/tenant/1234

####################### Clickhouse
@user = default
@pass = 
@base64Auth = {{user}}:{{pass}}

###
GET http://localhost:8123/ping
Authorization: Basic {{base64Auth}}

###
GET http://localhost:8123/?query=SHOW USERS
Authorization: Basic {{base64Auth}}

###
POST http://localhost:8123/?query=CREATE TABLE metricbox.events_tenant_123 AS metricbox.events_template
Authorization: Basic {{base64Auth}}

###
POST http://localhost:8123/?query=DROP TABLE IF EXISTS metricbox.events_tenant_123
Authorization: Basic {{base64Auth}}

###
GET http://localhost:8123/?query=SHOW TABLES IN metricbox
Authorization: Basic {{base64Auth}}

###
GET http://localhost:8123/?query=SELECT currentUser();
Authorization: Basic {{base64Auth}}