GET http://localhost:8080/health

###

POST http://localhost:8080/api/events
Content-Type: application/json

{
  "msg": "hello"
}

###

POST http://localhost:9090/admin/tenant/1234

###

DELETE http://localhost:9090/admin/tenant/1234